"""Create table blogged

Revision ID: 346a5842d3c2
Revises: 
Create Date: 2025-03-24 15:55:38.939656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346a5842d3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph', sa.String(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paragraphs')
    op.drop_table('stories')
    # ### end Alembic commands ###
